### ISSUE TITLE
Missing class in Create Widget

### ISSUE THREAD

**Issue by nyanilo** [staratlasmeta/FoundationKit#1]
Hi guys!

There is a missing class in the Create Widget. What class is supposed to be created there? Can I get a fix for it?

![image](https://user-images.githubusercontent.com/114026440/193100360-3a7d8947-a7a8-4b4b-90f1-e5eca63041bd.png)

**Comment by nyanilo** [comment]
Nope. I still have the same error. And WBP_Wallet is broken too. I see that the C++ functions are exposed to BP, so it seems that the project was compiled successfully.

I have followed all the installation steps and I even compiled the project from VS before running Unreal Editor. 

![image](https://user-images.githubusercontent.com/114026440/193125173-70b2bc28-d9cd-493c-93f5-8ed6f2d61863.png)

**Comment by rtorrisi** [comment]
@nyanilo I've been able to reproduce the issue, thank you for reporting this.
It should be fixed here 7929d9582ac60dbd3d00606749de4c8bca455ab6
